name: Prime workflow
on:
  workflow_dispatch:

jobs:
  primer-job:
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje de Bienvenida
        run: echo -e "\033[1;32m¡Bienvenidos a la presentación del GitHub Composite Action!\033[0m"
      - name: Mostrar Fecha y hora
        run: echo -e "\033[1;34mLa fecha y hora actual es $(date)\033[0m"
  segundo-job:
    runs-on: ubuntu-latest
    needs: primer-job
    steps:
      - name: Saludo personalizado
        run: echo -e "\033[1;36mHola, ${{ github.actor }}! Gracias por asistir.\033[0m"

      - name: Mensaje de despedida
        run: echo -e "\033[1;31m¡Gracias por su atención! ¡Hasta luego!\033[0m"

