
name: "Mi Composite actions"
description: "Este es un ejemplo de como crear una composite action"

inputs:
  artifact-name:
    description: "El nombre del artefacto a subir"
    required: false
    default: "app-react"
  
  upload-artifact:
    description: "El nombre del artefacto a subir"
    required: false
    default: false
  
  artifact-path:
    description: "La ruta del artefacto a subir"
    required: false
  
  node-version:
    description: "La versión de Node.js a usar"
    required: true
    default: "18"

outputs:
  artifact-url:
    description: "La URL del artefacto subido"
    value: ${{ steps.set-artifact-url.outputs.artifact-url }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        
    - name: Install Dependencies
      run: npm ci
      shell: bash
    
    - name: Run Tests
      run: npm test
      shell: bash
    
    - name: Upload Artifact
      if: ${{ inputs.upload-artifact == 'true' }}
      id: upload-artifact    
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }} 

    - name: Set Artifact URL
      if: ${{ inputs.upload-artifact == 'true' }}
      id: set-artifact-url
      run: echo "artifact-url=$(echo https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)" >> $GITHUB_OUTPUT
      shell: bash