name: Ejecución Composite Action
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: load & test the action
        uses: ./.github/actions/node-ci
     
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deployment via composite actions
        uses: ./.github/actions/node-cd
  